/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

//import Client.View.UserInfoGUI;
//import Main.MainGUI;
import Models.AdminAccount;
import Models.UserAccount;
import Server.Controller.ServerDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import keeptoo.Drag;

/**
 *
 * @author MyPC
 */
public class AdminLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminLoginGUI
     */
    
    ServerDAO dao;
    AdminAccount adminLogIn;
    
    public AdminLoginGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_Close = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        txt_AdminUserName = new javax.swing.JTextField();
        jLabel_Password = new javax.swing.JLabel();
        pas_AdminPassword = new javax.swing.JPasswordField();
        btn_LogIn = new keeptoo.KButton();
        pnl_Background = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(511, 323));
        setMinimumSize(new java.awt.Dimension(511, 323));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(511, 323));
        setSize(new java.awt.Dimension(511, 323));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 102));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin_settings_male_50px_white.png"))); // NOI18N
        jLabel1.setText("ADMINISTRATOR LOGIN");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        lbl_Close.setBackground(new java.awt.Color(0, 0, 255));
        lbl_Close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Close.setText("x");
        lbl_Close.setOpaque(true);
        lbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseExited(evt);
            }
        });
        kGradientPanel1.add(lbl_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 50));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Please enter to login...");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, 50));

        jLabel_UserName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_UserName.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_UserName.setText("Admin username:");
        getContentPane().add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 180, 40));

        txt_AdminUserName.setBackground(new java.awt.Color(102, 102, 102));
        txt_AdminUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_AdminUserName.setForeground(new java.awt.Color(255, 255, 255));
        txt_AdminUserName.setNextFocusableComponent(pas_AdminPassword);
        txt_AdminUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AdminUserNameFocusGained(evt);
            }
        });
        txt_AdminUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AdminUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_AdminUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 250, 50));

        jLabel_Password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_Password.setText("Admin Password:");
        getContentPane().add(jLabel_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, 40));

        pas_AdminPassword.setBackground(new java.awt.Color(102, 102, 102));
        pas_AdminPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pas_AdminPassword.setForeground(new java.awt.Color(255, 255, 255));
        pas_AdminPassword.setNextFocusableComponent(btn_LogIn);
        pas_AdminPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pas_AdminPasswordFocusGained(evt);
            }
        });
        pas_AdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas_AdminPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pas_AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 250, 50));

        btn_LogIn.setText("LOGIN");
        btn_LogIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_LogIn.setkHoverEndColor(new java.awt.Color(0, 0, 255));
        btn_LogIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_LogIn.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btn_LogIn.setkPressedColor(new java.awt.Color(255, 0, 0));
        btn_LogIn.setkSelectedColor(new java.awt.Color(255, 0, 0));
        btn_LogIn.setkStartColor(new java.awt.Color(0, 0, 255));
        btn_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogInActionPerformed(evt);
            }
        });
        getContentPane().add(btn_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, 130));

        pnl_Background.setkStartColor(new java.awt.Color(102, 102, 255));
        pnl_Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_BackgroundMouseDragged(evt);
            }
        });
        pnl_Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_BackgroundMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_BackgroundLayout = new javax.swing.GroupLayout(pnl_Background);
        pnl_Background.setLayout(pnl_BackgroundLayout);
        pnl_BackgroundLayout.setHorizontalGroup(
            pnl_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        pnl_BackgroundLayout.setVerticalGroup(
            pnl_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseClicked
        // TODO add your handling code here:
        if (lbl_Close.isFocusable())
            if (JOptionPane.showConfirmDialog(null, "Do you want exit? (Yes/No)","Warning!", 0)==0)
                System.exit(0);
//                this.dispose();
//                new Starting().setVisible(true);
    }//GEN-LAST:event_lbl_CloseMouseClicked

    private void lbl_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseEntered
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.red);
    }//GEN-LAST:event_lbl_CloseMouseEntered

    private void lbl_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseExited
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_CloseMouseExited

    private void txt_AdminUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AdminUserNameFocusGained
        // TODO add your handling code here:
        jLabel_UserName.setForeground(new Color(0, 204, 204));
        jLabel_Password.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_txt_AdminUserNameFocusGained

    private void pas_AdminPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pas_AdminPasswordFocusGained
        // TODO add your handling code here:
        jLabel_UserName.setForeground(new Color(255, 255, 255));
        jLabel_Password.setForeground(new Color(0, 204, 204));
    }//GEN-LAST:event_pas_AdminPasswordFocusGained

    
    // admin query----------------------------------------------------------
    
    private void btn_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogInActionPerformed
        // TODO add your handling code here:
        dao = new ServerDAO();
        String userName = txt_AdminUserName.getText();
        String userPass = String.valueOf(pas_AdminPassword.getPassword());

        if (txt_AdminUserName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Admin Username!");
        }
        else if (String.valueOf(pas_AdminPassword.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null,"Enter Admin Password!");
        }
        else if (dao.queryAdmin(userName, userPass)){
            adminLogIn = new AdminAccount();
            //            userLogIn.setUser_Username(userName);
            //            userLogIn.setUser_Password(userPass);
//            adminLogIn = dao.getInfo(userName, userPass);
            new AdminGUI(adminLogIn).setVisible(true); //Truyen tham so object member sau khi login thanh cong
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null,"Login Failed, try again!");
        }

    }//GEN-LAST:event_btn_LogInActionPerformed

    private void pnl_BackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BackgroundMousePressed
        // TODO add your handling code here:
        new Drag(rootPane).onPress(evt);
    }//GEN-LAST:event_pnl_BackgroundMousePressed

    private void txt_AdminUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AdminUserNameActionPerformed
        // TODO add your handling code here:
        btn_LogInActionPerformed(evt);
    }//GEN-LAST:event_txt_AdminUserNameActionPerformed

    private void pas_AdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas_AdminPasswordActionPerformed
        // TODO add your handling code here:
        btn_LogInActionPerformed(evt);
    }//GEN-LAST:event_pas_AdminPasswordActionPerformed

    private void pnl_BackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BackgroundMouseDragged
        // TODO add your handling code here:
        new Drag(rootPane).moveWindow(evt);
    }//GEN-LAST:event_pnl_BackgroundMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_UserName;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_Close;
    private javax.swing.JPasswordField pas_AdminPassword;
    private keeptoo.KGradientPanel pnl_Background;
    private javax.swing.JTextField txt_AdminUserName;
    // End of variables declaration//GEN-END:variables
}
