/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.Main;

import java.awt.Color;
import keeptoo.Drag;
import Client.View.UserLoginGUI;
import Models.Prize;
import Models.UserAccount;
import Server.Controller.ServerDAO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;



public class Starting extends javax.swing.JFrame {

    ArrayList<Prize> prizeList = new ArrayList<Prize>();
    ArrayList<UserAccount> topList = new ArrayList<UserAccount>();
    ServerDAO dao;
    
    
    public Starting() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        
        pnl_showIntroduction.setBackground(new Color(51, 51, 51, 50));
        pnl_showIntroduction.setBounds(220, 10, 770, 560);
        
        pnl_Intro.setBackground(new Color(51, 51, 51, 30));
        
        btn_Introduction.setBackground(new Color(51, 51, 51, 100));
        btn_Rules.setBackground(new Color(51, 51, 51, 100));
        btn_Ranking.setBackground(new Color(51, 51, 51, 100));
        btn_AboutUs.setBackground(new Color(51, 51, 51, 100));
        
        // Set Panel
        pnl_showIntroduction.setVisible(true);
        
        //panel Rules---------------------------------------
        pnl_showRules.setVisible(false);
        lbl_Rules.setBackground(new Color(0, 0, 255, 100));
        
        tbl_Rules.setShowGrid(true);
        dao = new ServerDAO();
        prizeList = dao.getRules();
        showRules();
        //--------------------------------------------------
        
        //panel Ranking-------------------------------------------
         topList = dao.getRanking();
         showRanking();
        //--------------------------------------------------------
        
        pnl_showRanking.setVisible(false);
        
        pnl_showAboutUs.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group_Intro = new javax.swing.ButtonGroup();
        kGradientPanel_Bg = new keeptoo.KGradientPanel();
        lbl_Close = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_Skip = new javax.swing.JLabel();
        pnl_Intro = new keeptoo.KGradientPanel();
        btn_Introduction = new javax.swing.JToggleButton();
        btn_Rules = new javax.swing.JToggleButton();
        btn_AboutUs = new javax.swing.JToggleButton();
        btn_Ranking = new javax.swing.JToggleButton();
        pnl_showIntroduction = new keeptoo.KGradientPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_Introduction = new javax.swing.JEditorPane();
        pnl_showRules = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Rules = new javax.swing.JTable();
        lbl_Rules = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_showRanking = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_Ranking1st = new javax.swing.JLabel();
        lbl_Ranking5th = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_Ranking2nd = new javax.swing.JLabel();
        lbl_Ranking3rd = new javax.swing.JLabel();
        lbl_Ranking4th = new javax.swing.JLabel();
        lbl_Ranking10th = new javax.swing.JLabel();
        lbl_Ranking7th = new javax.swing.JLabel();
        lbl_Ranking6th = new javax.swing.JLabel();
        lbl_Ranking8th = new javax.swing.JLabel();
        lbl_Ranking9th = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_showAboutUs = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));

        kGradientPanel_Bg.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel_Bg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kGradientPanel_Bg.setkBorderRadius(5);
        kGradientPanel_Bg.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel_Bg.setkGradientFocus(200);
        kGradientPanel_Bg.setkStartColor(new java.awt.Color(153, 153, 153));
        kGradientPanel_Bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel_BgMouseDragged(evt);
            }
        });
        kGradientPanel_Bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel_BgMousePressed(evt);
            }
        });
        kGradientPanel_Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Close.setBackground(new java.awt.Color(0, 0, 255));
        lbl_Close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Close.setText("x");
        lbl_Close.setOpaque(true);
        lbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseExited(evt);
            }
        });
        kGradientPanel_Bg.add(lbl_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 30));

        lbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_Aptech.png"))); // NOI18N
        lbl_Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel_Bg.add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        lbl_Skip.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_Skip.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Skip.setText("Continue..>>>");
        lbl_Skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SkipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_SkipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_SkipMouseExited(evt);
            }
        });
        kGradientPanel_Bg.add(lbl_Skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 160, 30));

        pnl_Intro.setkBorderRadius(20);
        pnl_Intro.setkEndColor(new java.awt.Color(255, 255, 255));
        pnl_Intro.setkFillBackground(false);
        pnl_Intro.setkGradientFocus(300);
        pnl_Intro.setkStartColor(new java.awt.Color(0, 0, 102));
        pnl_Intro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_IntroMouseEntered(evt);
            }
        });
        pnl_Intro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Group_Intro.add(btn_Introduction);
        btn_Introduction.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Introduction.setForeground(new java.awt.Color(255, 255, 255));
        btn_Introduction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_64px_white.png"))); // NOI18N
        btn_Introduction.setText("Introduction");
        btn_Introduction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Introduction.setMaximumSize(new java.awt.Dimension(110, 100));
        btn_Introduction.setMinimumSize(new java.awt.Dimension(110, 100));
        btn_Introduction.setPreferredSize(new java.awt.Dimension(110, 100));
        btn_Introduction.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_64px_red.png"))); // NOI18N
        btn_Introduction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Introduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IntroductionActionPerformed(evt);
            }
        });
        pnl_Intro.add(btn_Introduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 100));

        Group_Intro.add(btn_Rules);
        btn_Rules.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Rules.setForeground(new java.awt.Color(255, 255, 255));
        btn_Rules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_property_64px_white.png"))); // NOI18N
        btn_Rules.setText("RULES");
        btn_Rules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Rules.setMaximumSize(new java.awt.Dimension(110, 100));
        btn_Rules.setMinimumSize(new java.awt.Dimension(110, 100));
        btn_Rules.setPreferredSize(new java.awt.Dimension(110, 100));
        btn_Rules.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_property_64px_red.png"))); // NOI18N
        btn_Rules.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RulesActionPerformed(evt);
            }
        });
        pnl_Intro.add(btn_Rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 100));

        Group_Intro.add(btn_AboutUs);
        btn_AboutUs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btn_AboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about_64px_white.png"))); // NOI18N
        btn_AboutUs.setText("ABOUT US");
        btn_AboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_AboutUs.setMaximumSize(new java.awt.Dimension(110, 100));
        btn_AboutUs.setMinimumSize(new java.awt.Dimension(110, 100));
        btn_AboutUs.setPreferredSize(new java.awt.Dimension(110, 100));
        btn_AboutUs.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about_64px_red.png"))); // NOI18N
        btn_AboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AboutUsActionPerformed(evt);
            }
        });
        pnl_Intro.add(btn_AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 100));

        Group_Intro.add(btn_Ranking);
        btn_Ranking.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Ranking.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trophy_64px_white.png"))); // NOI18N
        btn_Ranking.setText("RANKING");
        btn_Ranking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Ranking.setMaximumSize(new java.awt.Dimension(110, 100));
        btn_Ranking.setMinimumSize(new java.awt.Dimension(110, 100));
        btn_Ranking.setPreferredSize(new java.awt.Dimension(110, 100));
        btn_Ranking.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trophy_64px_red.png"))); // NOI18N
        btn_Ranking.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RankingActionPerformed(evt);
            }
        });
        pnl_Intro.add(btn_Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, 100));

        kGradientPanel_Bg.add(pnl_Intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, 450));

        pnl_showIntroduction.setkBorderRadius(30);
        pnl_showIntroduction.setkEndColor(new java.awt.Color(51, 51, 255));
        pnl_showIntroduction.setkFillBackground(false);
        pnl_showIntroduction.setkStartColor(new java.awt.Color(0, 153, 255));
        pnl_showIntroduction.setMaximumSize(new java.awt.Dimension(770, 560));
        pnl_showIntroduction.setMinimumSize(new java.awt.Dimension(770, 560));
        pnl_showIntroduction.setOpaque(false);
        pnl_showIntroduction.setPreferredSize(new java.awt.Dimension(770, 560));
        pnl_showIntroduction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kbc_logo(160x160).png"))); // NOI18N
        pnl_showIntroduction.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        txt_Introduction.setEditable(false);
        txt_Introduction.setBackground(new java.awt.Color(51, 51, 51));
        txt_Introduction.setContentType("text/html"); // NOI18N
        txt_Introduction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_Introduction.setForeground(new java.awt.Color(0, 0, 153));
        txt_Introduction.setText("<html>\n<body>\n<p>\n<font size=\"18\" face=\"Tahoma\">\n<h2 style=\"text-align: center;\">KBC QUIZ</h2>\n<br><br><br>\n<h4 style=\"text-align: justify;\"><strong>&nbsp; &nbsp; &nbsp;Quiz show is generally organized to upgrade or the test the IQ level of</strong><strong>the person. It generally comprises question based on Current Affairs,</strong>\n<strong>Business, Events, History, General Knowledge, Science, Sports,</strong><strong>Articles and so on.It is organized for the sake of Gaining Knowledge as</strong><strong>well as for Entertainment purpose.</strong></h4>\n<h4 style=\"text-align: justify;\"><br /><strong>&nbsp; &nbsp; &nbsp;The company wants you to develop an online Quiz show game where</strong><strong>user can play the quiz game. For the entertainment sake they have</strong><strong>decided to add the prize money for the game which will keep on</strong>\n<strong>increasing with every question answered correctly, as per the table</strong><strong>below. Generation of the question should be random based, so that</strong>\n<strong>consecutive user does not get the repeated question and neither the</strong><strong>same user get that question again. Entering of the question should be</strong><strong>done by the Administrator only. Each user has to type their name then</strong>\n<strong>start playing the game. If the user answers the question incorrect then</strong><strong>final amount should generate and his/her page should get terminate.</strong><strong>Question should generate with four options where user has to select</strong>\n<strong>the one option at a time. User can leave the quiz before answering a</strong><strong>question by taking away the prize money upto question no.12.</strong><strong>Question 13 if attempted is mandatory to be answered. For Question</strong>\n<strong>1-12 user can view the question and then can decide to quit without</strong><strong>answering and taking away the earned money.</strong></h4>\n</font>\n</p>\n</body>\n</html>");
        txt_Introduction.setAutoscrolls(false);
        txt_Introduction.setOpaque(false);
        pnl_showIntroduction.add(txt_Introduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 540));

        kGradientPanel_Bg.add(pnl_showIntroduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 770, 560));

        pnl_showRules.setkBorderRadius(30);
        pnl_showRules.setkEndColor(new java.awt.Color(51, 51, 255));
        pnl_showRules.setkFillBackground(false);
        pnl_showRules.setkStartColor(new java.awt.Color(0, 153, 255));
        pnl_showRules.setMaximumSize(new java.awt.Dimension(770, 560));
        pnl_showRules.setMinimumSize(new java.awt.Dimension(770, 560));
        pnl_showRules.setOpaque(false);
        pnl_showRules.setPreferredSize(new java.awt.Dimension(770, 560));
        pnl_showRules.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 255), null, null));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbl_Rules.setBackground(new java.awt.Color(102, 102, 102));
        tbl_Rules.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_Rules.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbl_Rules.setForeground(new java.awt.Color(255, 255, 255));
        tbl_Rules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Right Answer", "Missed Answer", "Walk Away", "Wrong Answer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Rules.setAlignmentX(1.0F);
        tbl_Rules.setAlignmentY(1.0F);
        tbl_Rules.setColumnSelectionAllowed(true);
        tbl_Rules.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Rules.setOpaque(false);
        tbl_Rules.setRowHeight(22);
        tbl_Rules.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(tbl_Rules);
        tbl_Rules.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        pnl_showRules.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 710, 210));

        lbl_Rules.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_Rules.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Rules.setText("<html> While playing the game the user will have three life lines to save\nthem which can be used only once for the particular user<br>\n<br>○ 50-50:​ Out of the four options the two wrong answers will\nget erased, which makes only two options available for the\nuser.<br>\n<br>○ Flip:​ If the user feels he/she can’t answer the question\nthen they can flip the question and other question should\ngenerate automatically.<br>\n<br>○ Double dip:​ Here user gets two attempt to answer the\nquestion but are not allowed leaving the game if the first\nattempt goes wrong.</html>");
        lbl_Rules.setOpaque(true);
        pnl_showRules.add(lbl_Rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 710, 240));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kbc_logo(160x160).png"))); // NOI18N
        pnl_showRules.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RULES");
        pnl_showRules.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 250, 50));

        kGradientPanel_Bg.add(pnl_showRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 770, 560));

        pnl_showRanking.setkBorderRadius(30);
        pnl_showRanking.setkEndColor(new java.awt.Color(51, 51, 255));
        pnl_showRanking.setkFillBackground(false);
        pnl_showRanking.setkStartColor(new java.awt.Color(0, 153, 255));
        pnl_showRanking.setMaximumSize(new java.awt.Dimension(770, 560));
        pnl_showRanking.setMinimumSize(new java.awt.Dimension(770, 560));
        pnl_showRanking.setOpaque(false);
        pnl_showRanking.setPreferredSize(new java.awt.Dimension(770, 560));
        pnl_showRanking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOP REWARDS");
        pnl_showRanking.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kbc_logo(160x160).png"))); // NOI18N
        pnl_showRanking.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        lbl_Ranking1st.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_Ranking1st.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Ranking1st.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking1st.setText("Champion");
        lbl_Ranking1st.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking1st, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 450, 50));

        lbl_Ranking5th.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking5th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking5th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking5th.setText("5th");
        lbl_Ranking5th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking5th, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 290, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medal2_40px_gold.png"))); // NOI18N
        jLabel5.setText("Champion");
        pnl_showRanking.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 300, 40));

        lbl_Ranking2nd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking2nd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ranking2nd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking2nd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medal2_40px_silver.png"))); // NOI18N
        lbl_Ranking2nd.setText("Runners-up");
        lbl_Ranking2nd.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 430, 40));

        lbl_Ranking3rd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking3rd.setForeground(new java.awt.Color(255, 150, 0));
        lbl_Ranking3rd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking3rd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medal3_40px_copper.png"))); // NOI18N
        lbl_Ranking3rd.setText("Runners-up");
        lbl_Ranking3rd.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking3rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 390, 40));

        lbl_Ranking4th.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking4th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking4th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking4th.setText("4th");
        lbl_Ranking4th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking4th, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 40));

        lbl_Ranking10th.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking10th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking10th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking10th.setText("10th");
        lbl_Ranking10th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking10th, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 210, 40));

        lbl_Ranking7th.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking7th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking7th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking7th.setText("7th");
        lbl_Ranking7th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking7th, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 290, 40));

        lbl_Ranking6th.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking6th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking6th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking6th.setText("6th");
        lbl_Ranking6th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking6th, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 280, 40));

        lbl_Ranking8th.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking8th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking8th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking8th.setText("8th");
        lbl_Ranking8th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking8th, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 210, 40));

        lbl_Ranking9th.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Ranking9th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking9th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking9th.setText("9th");
        lbl_Ranking9th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_showRanking.add(lbl_Ranking9th, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 210, 40));
        pnl_showRanking.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 400, 20));

        kGradientPanel_Bg.add(pnl_showRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 770, 560));

        pnl_showAboutUs.setkBorderRadius(30);
        pnl_showAboutUs.setkEndColor(new java.awt.Color(51, 51, 255));
        pnl_showAboutUs.setkFillBackground(false);
        pnl_showAboutUs.setkStartColor(new java.awt.Color(0, 153, 255));
        pnl_showAboutUs.setMaximumSize(new java.awt.Dimension(770, 560));
        pnl_showAboutUs.setMinimumSize(new java.awt.Dimension(770, 560));
        pnl_showAboutUs.setOpaque(false);
        pnl_showAboutUs.setPreferredSize(new java.awt.Dimension(770, 560));
        pnl_showAboutUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kbc_logo(160x160).png"))); // NOI18N
        pnl_showAboutUs.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 150));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_Aptech.png"))); // NOI18N
        pnl_showAboutUs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GROUP 2");
        pnl_showAboutUs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 430, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROJECT:  SEM 2");
        pnl_showAboutUs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 390, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SUBJECT: KBC QUIZ");
        pnl_showAboutUs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 590, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CLASS: CP1796M04");
        pnl_showAboutUs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 390, 40));

        kGradientPanel_Bg.add(pnl_showAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 770, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel_Bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel_Bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel_BgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel_BgMousePressed
        // TODO add your handling code here:
        new Drag(rootPane).onPress(evt);
    }//GEN-LAST:event_kGradientPanel_BgMousePressed

    private void kGradientPanel_BgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel_BgMouseDragged
        // TODO add your handling code here:
        new Drag(rootPane).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel_BgMouseDragged

    private void lbl_SkipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SkipMouseEntered
        // TODO add your handling code here:
        lbl_Skip.setForeground(Color.red);
    }//GEN-LAST:event_lbl_SkipMouseEntered

    private void lbl_SkipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SkipMouseExited
        // TODO add your handling code here:
        lbl_Skip.setForeground(Color.white);
    }//GEN-LAST:event_lbl_SkipMouseExited

    private void lbl_SkipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SkipMouseClicked
        // TODO add your handling code here:
        new UserLoginGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_SkipMouseClicked

    private void pnl_IntroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_IntroMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnl_IntroMouseEntered

    private void btn_IntroductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IntroductionActionPerformed
        // TODO add your handling code here:
        pnl_showIntroduction.setVisible(true);
        
        
        pnl_showRules.setVisible(false);
        pnl_showRanking.setVisible(false);
        pnl_showAboutUs.setVisible(false);
    }//GEN-LAST:event_btn_IntroductionActionPerformed

    private void btn_RulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RulesActionPerformed
        // TODO add your handling code here:
        pnl_showRules.setVisible(true);
        
        
        pnl_showIntroduction.setVisible(false);
        pnl_showRanking.setVisible(false);
        pnl_showAboutUs.setVisible(false);
    }//GEN-LAST:event_btn_RulesActionPerformed

    private void btn_RankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RankingActionPerformed
        // TODO add your handling code here:
        pnl_showRanking.setVisible(true);
        
        
        pnl_showIntroduction.setVisible(false);
        pnl_showRules.setVisible(false);
        pnl_showAboutUs.setVisible(false);
    }//GEN-LAST:event_btn_RankingActionPerformed

    private void btn_AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AboutUsActionPerformed
        // TODO add your handling code here:
        pnl_showAboutUs.setVisible(true);
        
        
        pnl_showIntroduction.setVisible(false);
        pnl_showRules.setVisible(false);
        pnl_showRanking.setVisible(false);
    }//GEN-LAST:event_btn_AboutUsActionPerformed

    private void lbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseClicked
        // TODO add your handling code here:
        if (lbl_Close.isFocusable())
        if (JOptionPane.showConfirmDialog(null, "Do you want exit? (Yes/No)","Warning!", 0)==0)
        System.exit(0);
    }//GEN-LAST:event_lbl_CloseMouseClicked

    private void lbl_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseEntered
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.red);
    }//GEN-LAST:event_lbl_CloseMouseEntered

    private void lbl_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseExited
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_CloseMouseExited

    // Ranking show top 10 ------------------------------------------
    public void showRanking()
    {
        if (topList.get(0)!= null)
            lbl_Ranking1st.setText(topList.get(0).getUser_Username()+"($"+topList.get(0).getUser_HighestScore()+")");
        
        if (topList.get(1)!= null)
            lbl_Ranking2nd.setText(topList.get(1).getUser_Username()+"($"+topList.get(1).getUser_HighestScore()+")");
        
        if (topList.get(2)!= null)
            lbl_Ranking3rd.setText(topList.get(2).getUser_Username()+"($"+topList.get(2).getUser_HighestScore()+")");
        
        if (topList.get(3)!= null)
            lbl_Ranking4th.setText("4th "+topList.get(3).getUser_Username()+"($"+topList.get(3).getUser_HighestScore()+")");
        
        if (topList.get(4)!= null)
            lbl_Ranking5th.setText("5th "+topList.get(4).getUser_Username()+"($"+topList.get(4).getUser_HighestScore()+")");
        
        if (topList.get(5)!= null)
            lbl_Ranking6th.setText("6th "+topList.get(5).getUser_Username()+"($"+topList.get(5).getUser_HighestScore()+")");
        
        if (topList.get(6)!= null)
            lbl_Ranking7th.setText("7th "+topList.get(6).getUser_Username()+"($"+topList.get(6).getUser_HighestScore()+")");
        
        if (topList.get(7)!= null)
            lbl_Ranking8th.setText("8th "+topList.get(7).getUser_Username()+"($"+topList.get(7).getUser_HighestScore()+")");
        
        if (topList.get(8)!= null)
            lbl_Ranking9th.setText("9th "+topList.get(8).getUser_Username()+"($"+topList.get(8).getUser_HighestScore()+")");
        
        if (topList.get(9)!= null)
            lbl_Ranking10th.setText("10th "+topList.get(9).getUser_Username()+"($"+topList.get(9).getUser_HighestScore()+")");
        
    }
    //---------------------------------------------------------------
    
    // Table Rules show--------------------------------------------------
    public void showRules()
    {
        
        DefaultTableModel tblModel = (DefaultTableModel)tbl_Rules.getModel();
        
        //set Alignment Column
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        int column = 5;
        for (int c = 0; c<column;c++){
        tbl_Rules.getColumnModel().getColumn(c).setCellRenderer(centerRenderer);
        }
        
        Object[] row = new Object[column];
        for(int i=0;i<prizeList.size();i++){
            
            row[0]=prizeList.get(i).getPrize_ID();
            row[1]=prizeList.get(i).getPrize_RightAnswer();
            row[2]=prizeList.get(i).getPrize_MissAnswer();
            row[3]=prizeList.get(i).getPrize_WalkAway();
            row[4]=prizeList.get(i).getPrize_WrongAnswer();
            
            tblModel.addRow(row);
        }
    }
    //-------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Starting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Starting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Starting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Starting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Starting().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Starting.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group_Intro;
    private javax.swing.JToggleButton btn_AboutUs;
    private javax.swing.JToggleButton btn_Introduction;
    private javax.swing.JToggleButton btn_Ranking;
    private javax.swing.JToggleButton btn_Rules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel_Bg;
    private javax.swing.JLabel lbl_Close;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Ranking10th;
    private javax.swing.JLabel lbl_Ranking1st;
    private javax.swing.JLabel lbl_Ranking2nd;
    private javax.swing.JLabel lbl_Ranking3rd;
    private javax.swing.JLabel lbl_Ranking4th;
    private javax.swing.JLabel lbl_Ranking5th;
    private javax.swing.JLabel lbl_Ranking6th;
    private javax.swing.JLabel lbl_Ranking7th;
    private javax.swing.JLabel lbl_Ranking8th;
    private javax.swing.JLabel lbl_Ranking9th;
    private javax.swing.JLabel lbl_Rules;
    private javax.swing.JLabel lbl_Skip;
    private keeptoo.KGradientPanel pnl_Intro;
    private keeptoo.KGradientPanel pnl_showAboutUs;
    private keeptoo.KGradientPanel pnl_showIntroduction;
    private keeptoo.KGradientPanel pnl_showRanking;
    private keeptoo.KGradientPanel pnl_showRules;
    private javax.swing.JTable tbl_Rules;
    private javax.swing.JEditorPane txt_Introduction;
    // End of variables declaration//GEN-END:variables
}
