/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.View;

import Client.Main.Starting;
import Models.Prize;
import Models.UserAccount;
import Server.Controller.ServerDAO;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import keeptoo.Drag;

/**
 *
 * @author MyPC
 */
public class UserInfoGUI extends javax.swing.JFrame {

    ArrayList<UserAccount> topList = new ArrayList<UserAccount>();
    ServerDAO dao = new ServerDAO();
    
//    UserAccount member = UserLoginGUI.userLogIn;
    UserAccount member;
    Prize prize;
    ArrayList<Prize> prizeList = new ArrayList<>();
    public UserInfoGUI() {
        initComponents();
        setLocationRelativeTo(null);
        lbl_Member.setText("Member");
        
        tbl_Rules.setShowGrid(true);
        
    }
    public UserInfoGUI(UserAccount user) {
        initComponents();
        
        this.member = user;
        
        setLocationRelativeTo(null);
        String username = member.getUser_Username();
        
        lbl_Member.setText(username);
        lbl_MemberInfo.setText(username+"'s information..");
        //panel Information
        showInfo();

        
        //new load panel
        btn_Rules.setSelected(false);
        btn_Ranking.setSelected(false);
                
        pnl_ShowInfo.setVisible(true);
        pnl_ShowRanking.setVisible(false);
        pnl_ShowRules.setVisible(false);
        

        //panel Rules
        tbl_Rules.setShowGrid(true);
        ServerDAO dao = new ServerDAO();
        prizeList = dao.getRules();
        showRules();
        
        //panel Ranking-------------------------------------------
         topList = dao.getRanking();
         showRanking();
        //--------------------------------------------------------
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group1 = new javax.swing.ButtonGroup();
        tbl_Rules1 = new javax.swing.JTable();
        pnl_Background = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lbl_Close = new javax.swing.JLabel();
        lbl_Title = new javax.swing.JLabel();
        lbl_LogOut = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        lbl_Hello = new javax.swing.JLabel();
        lbl_Member = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_Rules = new javax.swing.JToggleButton();
        btn_Ranking = new javax.swing.JToggleButton();
        lbl_Play = new javax.swing.JLabel();
        pnl_ShowInfo = new keeptoo.KGradientPanel();
        lbl_MemberInfo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_FullName = new javax.swing.JLabel();
        lbl_Phone = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        lbl_BestScore = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        pnl_ShowRules = new keeptoo.KGradientPanel();
        lbl_MemberInfo1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Rules = new javax.swing.JTable();
        lbl_Rules = new javax.swing.JLabel();
        pnl_ShowRanking = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_Ranking1st = new javax.swing.JLabel();
        lbl_Ranking5th = new javax.swing.JLabel();
        lbl_Ranking2nd = new javax.swing.JLabel();
        lbl_Ranking3rd = new javax.swing.JLabel();
        lbl_Ranking4th = new javax.swing.JLabel();
        lbl_Ranking10th = new javax.swing.JLabel();
        lbl_Ranking7th = new javax.swing.JLabel();
        lbl_Ranking6th = new javax.swing.JLabel();
        lbl_Ranking8th = new javax.swing.JLabel();
        lbl_Ranking9th = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();

        tbl_Rules1.setBackground(new java.awt.Color(102, 102, 102));
        tbl_Rules1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_Rules1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbl_Rules1.setForeground(new java.awt.Color(255, 255, 255));
        tbl_Rules1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Right Answer", "Missed Answer", "Walk Away", "Wrong Answer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Rules1.setAlignmentX(1.0F);
        tbl_Rules1.setAlignmentY(1.0F);
        tbl_Rules1.setColumnSelectionAllowed(true);
        tbl_Rules1.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Rules1.setOpaque(false);
        tbl_Rules1.setRowHeight(22);
        tbl_Rules1.getTableHeader().setResizingAllowed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnl_Background.setMaximumSize(new java.awt.Dimension(600, 450));
        pnl_Background.setMinimumSize(new java.awt.Dimension(600, 450));

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 51, 255));
        kGradientPanel2.setkGradientFocus(200);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Close.setBackground(new java.awt.Color(0, 0, 255));
        lbl_Close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Close.setText("x");
        lbl_Close.setOpaque(true);
        lbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseExited(evt);
            }
        });
        kGradientPanel2.add(lbl_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, 50));

        lbl_Title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_male_circle_64px_white.png"))); // NOI18N
        lbl_Title.setText("USER INFORMATION");
        kGradientPanel2.add(lbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 50));

        lbl_LogOut.setBackground(new java.awt.Color(0, 0, 255));
        lbl_LogOut.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbl_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_LogOut.setText("Log Out");
        lbl_LogOut.setOpaque(true);
        lbl_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_LogOutMouseExited(evt);
            }
        });
        kGradientPanel2.add(lbl_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 90, 50));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        kGradientPanel3.setkBorderRadius(30);
        kGradientPanel3.setkEndColor(new java.awt.Color(102, 102, 102));
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 153, 153));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Hello.setBackground(new java.awt.Color(153, 153, 153));
        lbl_Hello.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Hello.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Hello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Hello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/circled_user_100px_blue.png"))); // NOI18N
        lbl_Hello.setText("Welcome");
        lbl_Hello.setToolTipText("Click here your information..");
        lbl_Hello.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Hello.setOpaque(true);
        lbl_Hello.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Hello.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HelloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_HelloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_HelloMouseExited(evt);
            }
        });
        kGradientPanel3.add(lbl_Hello, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 120));

        lbl_Member.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Member.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Member.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kGradientPanel3.add(lbl_Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, 30));
        kGradientPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 10));

        btn_Rules.setBackground(new java.awt.Color(51, 51, 51));
        btn_Rules.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Rules.setForeground(new java.awt.Color(255, 255, 255));
        btn_Rules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_property_64px_white.png"))); // NOI18N
        btn_Rules.setText("RULES");
        btn_Rules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Rules.setMaximumSize(new java.awt.Dimension(110, 100));
        btn_Rules.setMinimumSize(new java.awt.Dimension(110, 100));
        btn_Rules.setOpaque(true);
        btn_Rules.setPreferredSize(new java.awt.Dimension(110, 100));
        btn_Rules.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_property_64px_red.png"))); // NOI18N
        btn_Rules.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_property_64px_red.png"))); // NOI18N
        btn_Rules.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_property_64px_red.png"))); // NOI18N
        btn_Rules.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RulesActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btn_Rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 100));

        btn_Ranking.setBackground(new java.awt.Color(51, 51, 51));
        btn_Ranking.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Ranking.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trophy_64px_white.png"))); // NOI18N
        btn_Ranking.setText("RANKING");
        btn_Ranking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Ranking.setMaximumSize(new java.awt.Dimension(110, 100));
        btn_Ranking.setMinimumSize(new java.awt.Dimension(110, 100));
        btn_Ranking.setOpaque(true);
        btn_Ranking.setPreferredSize(new java.awt.Dimension(110, 100));
        btn_Ranking.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trophy_64px_red.png"))); // NOI18N
        btn_Ranking.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trophy_64px_red.png"))); // NOI18N
        btn_Ranking.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trophy_64px_red.png"))); // NOI18N
        btn_Ranking.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RankingActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btn_Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, 100));

        lbl_Play.setBackground(new java.awt.Color(0, 0, 255));
        lbl_Play.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Play.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Play.setText("PLAY");
        lbl_Play.setOpaque(true);
        lbl_Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_PlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_PlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_PlayMouseExited(evt);
            }
        });
        kGradientPanel3.add(lbl_Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 30));

        kGradientPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 410));

        pnl_ShowInfo.setkBorderRadius(0);
        pnl_ShowInfo.setkEndColor(new java.awt.Color(51, 51, 51));
        pnl_ShowInfo.setkStartColor(new java.awt.Color(153, 153, 153));
        pnl_ShowInfo.setMaximumSize(new java.awt.Dimension(470, 410));
        pnl_ShowInfo.setMinimumSize(new java.awt.Dimension(470, 410));
        pnl_ShowInfo.setPreferredSize(new java.awt.Dimension(470, 410));
        pnl_ShowInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MemberInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_MemberInfo.setForeground(new java.awt.Color(0, 0, 255));
        pnl_ShowInfo.add(lbl_MemberInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 30, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Phone:");
        pnl_ShowInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Best Prize:");
        pnl_ShowInfo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        pnl_ShowInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        pnl_ShowInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Full name:");
        pnl_ShowInfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        lbl_FullName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbl_FullName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FullName.setText("Full name");
        pnl_ShowInfo.add(lbl_FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 300, 30));

        lbl_Phone.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbl_Phone.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Phone.setText("Phone");
        pnl_ShowInfo.add(lbl_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 260, 30));

        lbl_Email.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Email.setText("Email");
        pnl_ShowInfo.add(lbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 260, 30));

        lbl_Address.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbl_Address.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Address.setText("Address");
        pnl_ShowInfo.add(lbl_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 260, 30));

        lbl_BestScore.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lbl_BestScore.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BestScore.setText("Best Score");
        pnl_ShowInfo.add(lbl_BestScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 110, 30));
        pnl_ShowInfo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 5));
        pnl_ShowInfo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 440, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(0, 5));
        pnl_ShowInfo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 440, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        pnl_ShowInfo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 410, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        pnl_ShowInfo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 410, 10));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        pnl_ShowInfo.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 410, 10));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        pnl_ShowInfo.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 410, 10));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        pnl_ShowInfo.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 210, 10));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        pnl_ShowInfo.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 210, 10));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 30, 30));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 30, 30));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 30, 120));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 30, 120));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 30, 30));

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 30, 30));

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_ShowInfo.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 30, 30));

        kGradientPanel1.add(pnl_ShowInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 470, 400));

        pnl_ShowRules.setAutoscrolls(true);
        pnl_ShowRules.setkBorderRadius(0);
        pnl_ShowRules.setkEndColor(new java.awt.Color(51, 51, 51));
        pnl_ShowRules.setkStartColor(new java.awt.Color(153, 153, 153));
        pnl_ShowRules.setMaximumSize(new java.awt.Dimension(470, 410));
        pnl_ShowRules.setMinimumSize(new java.awt.Dimension(470, 410));
        pnl_ShowRules.setPreferredSize(new java.awt.Dimension(470, 410));
        pnl_ShowRules.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MemberInfo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_MemberInfo1.setForeground(new java.awt.Color(0, 0, 255));
        lbl_MemberInfo1.setText("Rules of KBC's Quiz");
        pnl_ShowRules.add(lbl_MemberInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 30));
        pnl_ShowRules.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 10));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 255), null, null));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbl_Rules.setBackground(new java.awt.Color(102, 102, 102));
        tbl_Rules.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_Rules.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbl_Rules.setForeground(new java.awt.Color(255, 255, 255));
        tbl_Rules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Right Answer", "Missed Answer", "Walk Away", "Wrong Answer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Rules.setAlignmentX(1.0F);
        tbl_Rules.setAlignmentY(1.0F);
        tbl_Rules.setColumnSelectionAllowed(true);
        tbl_Rules.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Rules.setOpaque(false);
        tbl_Rules.setRowHeight(22);
        tbl_Rules.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(tbl_Rules);
        tbl_Rules.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tbl_Rules.getColumnModel().getColumnCount() > 0) {
            tbl_Rules.getColumnModel().getColumn(0).setResizable(false);
            tbl_Rules.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbl_Rules.getColumnModel().getColumn(0).setHeaderValue("No.");
            tbl_Rules.getColumnModel().getColumn(1).setResizable(false);
            tbl_Rules.getColumnModel().getColumn(1).setHeaderValue("Right Answer");
            tbl_Rules.getColumnModel().getColumn(2).setResizable(false);
            tbl_Rules.getColumnModel().getColumn(2).setHeaderValue("Missed Answer");
            tbl_Rules.getColumnModel().getColumn(3).setResizable(false);
            tbl_Rules.getColumnModel().getColumn(3).setHeaderValue("Walk Away");
            tbl_Rules.getColumnModel().getColumn(4).setResizable(false);
            tbl_Rules.getColumnModel().getColumn(4).setHeaderValue("Wrong Answer");
        }

        pnl_ShowRules.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 450, 130));

        lbl_Rules.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Rules.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Rules.setText("<html>While playing the game the user will have three life lines to save\nthem which can be used only once for the particular user\n<br>○ 50-50:​ Out of the four options the two wrong answers will\nget erased, which makes only two options available for the\nuser.\n<br>○ Flip:​ If the user feels he/she can’t answer the question\nthen they can flip the question and other question should\ngenerate automatically.\n<br>○ Double dip:​ Here user gets two attempt to answer the\nquestion but are not allowed leaving the game if the first\nattempt goes wrong.</html>");
        pnl_ShowRules.add(lbl_Rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 180));

        kGradientPanel1.add(pnl_ShowRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 470, 400));

        pnl_ShowRanking.setkBorderRadius(0);
        pnl_ShowRanking.setkEndColor(new java.awt.Color(51, 51, 51));
        pnl_ShowRanking.setkStartColor(new java.awt.Color(153, 153, 153));
        pnl_ShowRanking.setMaximumSize(new java.awt.Dimension(470, 410));
        pnl_ShowRanking.setMinimumSize(new java.awt.Dimension(470, 410));
        pnl_ShowRanking.setPreferredSize(new java.awt.Dimension(470, 410));
        pnl_ShowRanking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOP REWARDS");
        pnl_ShowRanking.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 290, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kbc_logo(160x160).png"))); // NOI18N
        pnl_ShowRanking.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        lbl_Ranking1st.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking1st.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Ranking1st.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking1st.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medal2_40px_gold.png"))); // NOI18N
        lbl_Ranking1st.setText("Champion");
        lbl_Ranking1st.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking1st, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 290, 40));

        lbl_Ranking5th.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking5th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking5th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking5th.setText("5th");
        lbl_Ranking5th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking5th, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 220, 40));

        lbl_Ranking2nd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking2nd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ranking2nd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking2nd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medal2_40px_silver.png"))); // NOI18N
        lbl_Ranking2nd.setText("Runners-up");
        lbl_Ranking2nd.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 290, 40));

        lbl_Ranking3rd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking3rd.setForeground(new java.awt.Color(255, 150, 0));
        lbl_Ranking3rd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking3rd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medal3_40px_copper.png"))); // NOI18N
        lbl_Ranking3rd.setText("Runners-up");
        lbl_Ranking3rd.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking3rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 290, 40));

        lbl_Ranking4th.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking4th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking4th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking4th.setText("4th");
        lbl_Ranking4th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking4th, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 40));

        lbl_Ranking10th.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking10th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking10th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking10th.setText("10th");
        lbl_Ranking10th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking10th, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 220, 40));

        lbl_Ranking7th.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking7th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking7th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking7th.setText("7th");
        lbl_Ranking7th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking7th, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 220, 40));

        lbl_Ranking6th.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking6th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking6th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking6th.setText("6th");
        lbl_Ranking6th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking6th, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, 40));

        lbl_Ranking8th.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking8th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking8th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking8th.setText("8th");
        lbl_Ranking8th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking8th, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 220, 40));

        lbl_Ranking9th.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ranking9th.setForeground(new java.awt.Color(102, 102, 255));
        lbl_Ranking9th.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ranking9th.setText("9th");
        lbl_Ranking9th.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        pnl_ShowRanking.add(lbl_Ranking9th, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 220, 40));
        pnl_ShowRanking.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 270, 10));

        kGradientPanel1.add(pnl_ShowRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 470, 400));

        javax.swing.GroupLayout pnl_BackgroundLayout = new javax.swing.GroupLayout(pnl_Background);
        pnl_Background.setLayout(pnl_BackgroundLayout);
        pnl_BackgroundLayout.setHorizontalGroup(
            pnl_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        pnl_BackgroundLayout.setVerticalGroup(
            pnl_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_CloseMouseClicked

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        new Drag(rootPane).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        new Drag(rootPane).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void lbl_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseEntered
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.red);
    }//GEN-LAST:event_lbl_CloseMouseEntered

    private void lbl_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseExited
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_CloseMouseExited

    private void btn_RulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RulesActionPerformed
        // TODO add your handling code here:
        
        
        btn_Ranking.setSelected(false);
        pnl_ShowRanking.setVisible(false);
        
        pnl_ShowInfo.setVisible(false);
        
        btn_Rules.setSelected(true);
        pnl_ShowRules.setVisible(true);

    }//GEN-LAST:event_btn_RulesActionPerformed

    private void lbl_HelloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HelloMouseEntered
        // TODO add your handling code here:
        lbl_Hello.setBackground(new Color(204, 204, 204, 255));
//        Icon image = new Icon("/images/circled_user_100px_blue.png");
//        lbl_Hello.setIcon();
    }//GEN-LAST:event_lbl_HelloMouseEntered

    private void lbl_HelloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HelloMouseExited
        // TODO add your handling code here:
        lbl_Hello.setBackground(new Color(153, 153, 153, 255));
    }//GEN-LAST:event_lbl_HelloMouseExited

    private void btn_RankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RankingActionPerformed
        // TODO add your handling code here:
        btn_Ranking.setSelected(true);
        pnl_ShowRanking.setVisible(true);
        
        pnl_ShowInfo.setVisible(false);
        
        btn_Rules.setSelected(false);
        pnl_ShowRules.setVisible(false);
    }//GEN-LAST:event_btn_RankingActionPerformed

    private void lbl_HelloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HelloMouseClicked
        // TODO add your handling code here:
        btn_Ranking.setSelected(false);
        pnl_ShowRanking.setVisible(false);
        
        pnl_ShowInfo.setVisible(true);
        
        btn_Rules.setSelected(false);
        pnl_ShowRules.setVisible(false);
    }//GEN-LAST:event_lbl_HelloMouseClicked

    private void lbl_PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PlayMouseClicked
        // TODO add your handling code here:
        new PlayingGUI(member).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_PlayMouseClicked

    private void lbl_PlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PlayMouseEntered
        // TODO add your handling code here:
        lbl_Play.setBackground(Color.red);
    }//GEN-LAST:event_lbl_PlayMouseEntered

    private void lbl_PlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PlayMouseExited
        // TODO add your handling code here:
        lbl_Play.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_PlayMouseExited

    private void lbl_LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOutMouseEntered
        // TODO add your handling code here:
        lbl_LogOut.setBackground(Color.red);
    }//GEN-LAST:event_lbl_LogOutMouseEntered

    private void lbl_LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOutMouseExited
        // TODO add your handling code here:
        lbl_LogOut.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_LogOutMouseExited

    private void lbl_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOutMouseClicked
        // TODO add your handling code here:
//        member = new UserAccount();
        member = null;
        try {
            new Starting().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(UserInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_lbl_LogOutMouseClicked
    
    public void showInfo()
    {
        lbl_FullName.setText(member.getUser_Fullname());
        lbl_Phone.setText(member.getUser_Phone());
        lbl_Email.setText(member.getUser_Mail());
        lbl_Address.setText(member.getUser_Address());
        lbl_BestScore.setText(String.valueOf(member.getUser_HighestScore()));
    }
    
    public void showRules()
    {
        
        DefaultTableModel tblModel = (DefaultTableModel)tbl_Rules.getModel();
        
        //set Alignment Column
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        int column = 5;
        for (int c = 0; c<column;c++){
        tbl_Rules.getColumnModel().getColumn(c).setCellRenderer(centerRenderer);
        }
        
        Object[] row = new Object[column];
        for(int i=0;i<prizeList.size();i++){
            
            row[0]=prizeList.get(i).getPrize_ID();
            row[1]=prizeList.get(i).getPrize_RightAnswer();
            row[2]=prizeList.get(i).getPrize_MissAnswer();
            row[3]=prizeList.get(i).getPrize_WalkAway();
            row[4]=prizeList.get(i).getPrize_WrongAnswer();
            
            tblModel.addRow(row);
        }
    }
    
    // Ranking show top 10 ------------------------------------------
    public void showRanking()
    {
        if (topList.get(0)!= null)
            lbl_Ranking1st.setText(topList.get(0).getUser_Username()+"($"+topList.get(0).getUser_HighestScore()+")");
        
        if (topList.get(1)!= null)
            lbl_Ranking2nd.setText(topList.get(1).getUser_Username()+"($"+topList.get(1).getUser_HighestScore()+")");
        
        if (topList.get(2)!= null)
            lbl_Ranking3rd.setText(topList.get(2).getUser_Username()+"($"+topList.get(2).getUser_HighestScore()+")");
        
        if (topList.get(3)!= null)
            lbl_Ranking4th.setText("4th "+topList.get(3).getUser_Username()+"($"+topList.get(3).getUser_HighestScore()+")");
        
        if (topList.get(4)!= null)
            lbl_Ranking5th.setText("5th "+topList.get(4).getUser_Username()+"($"+topList.get(4).getUser_HighestScore()+")");
        
        if (topList.get(5)!= null)
            lbl_Ranking6th.setText("6th "+topList.get(5).getUser_Username()+"($"+topList.get(5).getUser_HighestScore()+")");
        
        if (topList.get(6)!= null)
            lbl_Ranking7th.setText("7th "+topList.get(6).getUser_Username()+"($"+topList.get(6).getUser_HighestScore()+")");
        
        if (topList.get(7)!= null)
            lbl_Ranking8th.setText("8th "+topList.get(7).getUser_Username()+"($"+topList.get(7).getUser_HighestScore()+")");
        
        if (topList.get(8)!= null)
            lbl_Ranking9th.setText("9th "+topList.get(8).getUser_Username()+"($"+topList.get(8).getUser_HighestScore()+")");
        
        if (topList.get(9)!= null)
            lbl_Ranking10th.setText("10th "+topList.get(9).getUser_Username()+"($"+topList.get(9).getUser_HighestScore()+")");
        
    }
    //---------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group1;
    private javax.swing.JToggleButton btn_Ranking;
    private javax.swing.JToggleButton btn_Rules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_BestScore;
    private javax.swing.JLabel lbl_Close;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_FullName;
    private javax.swing.JLabel lbl_Hello;
    private javax.swing.JLabel lbl_LogOut;
    private javax.swing.JLabel lbl_Member;
    private javax.swing.JLabel lbl_MemberInfo;
    private javax.swing.JLabel lbl_MemberInfo1;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_Play;
    private javax.swing.JLabel lbl_Ranking10th;
    private javax.swing.JLabel lbl_Ranking1st;
    private javax.swing.JLabel lbl_Ranking2nd;
    private javax.swing.JLabel lbl_Ranking3rd;
    private javax.swing.JLabel lbl_Ranking4th;
    private javax.swing.JLabel lbl_Ranking5th;
    private javax.swing.JLabel lbl_Ranking6th;
    private javax.swing.JLabel lbl_Ranking7th;
    private javax.swing.JLabel lbl_Ranking8th;
    private javax.swing.JLabel lbl_Ranking9th;
    private javax.swing.JLabel lbl_Rules;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel pnl_Background;
    private keeptoo.KGradientPanel pnl_ShowInfo;
    private keeptoo.KGradientPanel pnl_ShowRanking;
    private keeptoo.KGradientPanel pnl_ShowRules;
    private javax.swing.JTable tbl_Rules;
    private javax.swing.JTable tbl_Rules1;
    // End of variables declaration//GEN-END:variables
}
