/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.View;

import Models.Prize;
import Models.UserAccount;
import Server.Controller.ServerDAO;
import java.awt.Color;
import keeptoo.Drag;

/**
 *
 * @author MyPC
 */


public class UserRewardGUI extends javax.swing.JFrame {

    /**
     * Creates new form UserRewardGUI
     */
    
    ServerDAO dao = new ServerDAO();
    
    UserAccount member;
    Prize prize;
    
    public UserRewardGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public UserRewardGUI(UserAccount user) {
        initComponents();
        this.member = user;
        
        setLocationRelativeTo(null);
        String username = member.getUser_Username();
        
        lbl_Member.setText(username);
        
        lbl_Prize.setText("$ "+String.valueOf(member.getUser_NumberOfAttendance()));
        
        // Update prize to SQL
        dao.setPrize(member, member.getUser_HighestScore(), member.getUser_NumberOfAttendance());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new keeptoo.KGradientPanel();
        lbl_Member = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_Prize = new javax.swing.JLabel();
        lbl_Close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setkEndColor(new java.awt.Color(51, 51, 51));
        bg.setkGradientFocus(100);
        bg.setkStartColor(new java.awt.Color(153, 153, 153));
        bg.setMaximumSize(new java.awt.Dimension(500, 300));
        bg.setMinimumSize(new java.awt.Dimension(500, 300));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Member.setBackground(new java.awt.Color(51, 51, 255));
        lbl_Member.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_Member.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Member.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/circled_user_100px_white.png"))); // NOI18N
        lbl_Member.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Member.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bg.add(lbl_Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YOUR PRIZE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 270, 50));

        lbl_Prize.setFont(new java.awt.Font("Quartz", 1, 90)); // NOI18N
        lbl_Prize.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Prize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Prize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(lbl_Prize, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 460, 130));

        lbl_Close.setBackground(new java.awt.Color(0, 0, 255));
        lbl_Close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Close.setText("x");
        lbl_Close.setOpaque(true);
        lbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseExited(evt);
            }
        });
        bg.add(lbl_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 40));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseClicked
        // TODO add your handling code here:
        new UserInfoGUI(member).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_CloseMouseClicked

    private void lbl_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseEntered
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.red);
    }//GEN-LAST:event_lbl_CloseMouseEntered

    private void lbl_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseExited
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_CloseMouseExited

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        // TODO add your handling code here:
        new Drag(rootPane).moveWindow(evt);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        new Drag(rootPane).onPress(evt);
    }//GEN-LAST:event_bgMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRewardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRewardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRewardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRewardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRewardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Close;
    private javax.swing.JLabel lbl_Member;
    private javax.swing.JLabel lbl_Prize;
    // End of variables declaration//GEN-END:variables
}
