/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.View;

import Client.Main.Starting;
import Main.MainGUI;
import Models.UserAccount;
import Server.Controller.ServerDAO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import keeptoo.Drag;

/**
 *
 * @author MyPC
 */
public class UserLoginGUI extends javax.swing.JFrame {

    UserAccount member;
    // Creates User Login
    
//    UserAccount userLogIn;
    ServerDAO dao;
    
    public UserLoginGUI() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    public UserLoginGUI(UserAccount user) {
        initComponents();
        setLocationRelativeTo(null);
        this.member = user;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel_Bg = new keeptoo.KGradientPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_Close = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        pas_UserPassword = new javax.swing.JPasswordField();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_LogIn = new keeptoo.KButton();
        lbl_CreateAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 505, 336));
        setMinimumSize(new java.awt.Dimension(505, 336));
        setUndecorated(true);
        setSize(new java.awt.Dimension(505, 336));

        kGradientPanel_Bg.setkBorderRadius(20);
        kGradientPanel_Bg.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel_Bg.setkGradientFocus(200);
        kGradientPanel_Bg.setkStartColor(new java.awt.Color(153, 153, 153));
        kGradientPanel_Bg.setMaximumSize(new java.awt.Dimension(505, 336));
        kGradientPanel_Bg.setMinimumSize(new java.awt.Dimension(505, 336));
        kGradientPanel_Bg.setPreferredSize(new java.awt.Dimension(505, 336));
        kGradientPanel_Bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel_BgMouseDragged(evt);
            }
        });
        kGradientPanel_Bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel_BgMousePressed(evt);
            }
        });
        kGradientPanel_Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 255));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_male_circle_64px_white.png"))); // NOI18N
        jLabel1.setText("USER LOGIN");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        lbl_Close.setBackground(new java.awt.Color(0, 0, 255));
        lbl_Close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Close.setText("x");
        lbl_Close.setOpaque(true);
        lbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseExited(evt);
            }
        });
        kGradientPanel1.add(lbl_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 50));

        kGradientPanel_Bg.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 50));

        txt_UserName.setBackground(new java.awt.Color(102, 102, 102));
        txt_UserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_UserName.setForeground(new java.awt.Color(255, 255, 255));
        txt_UserName.setNextFocusableComponent(pas_UserPassword);
        txt_UserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_UserNameFocusGained(evt);
            }
        });
        txt_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserNameActionPerformed(evt);
            }
        });
        kGradientPanel_Bg.add(txt_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 250, 50));

        pas_UserPassword.setBackground(new java.awt.Color(102, 102, 102));
        pas_UserPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pas_UserPassword.setForeground(new java.awt.Color(255, 255, 255));
        pas_UserPassword.setNextFocusableComponent(btn_LogIn);
        pas_UserPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pas_UserPasswordFocusGained(evt);
            }
        });
        pas_UserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas_UserPasswordActionPerformed(evt);
            }
        });
        kGradientPanel_Bg.add(pas_UserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 250, 50));

        jLabel_UserName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_UserName.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_UserName.setText("User name:");
        kGradientPanel_Bg.add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 110, 40));

        jLabel_Password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_Password.setText("Password:");
        kGradientPanel_Bg.add(jLabel_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Please enter to login...");
        kGradientPanel_Bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, 50));

        btn_LogIn.setText("LOGIN");
        btn_LogIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_LogIn.setkHoverEndColor(new java.awt.Color(0, 0, 255));
        btn_LogIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_LogIn.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btn_LogIn.setkPressedColor(new java.awt.Color(255, 0, 0));
        btn_LogIn.setkSelectedColor(new java.awt.Color(255, 0, 0));
        btn_LogIn.setkStartColor(new java.awt.Color(0, 0, 255));
        btn_LogIn.setNextFocusableComponent(lbl_CreateAccount);
        btn_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogInActionPerformed(evt);
            }
        });
        kGradientPanel_Bg.add(btn_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, 130));

        lbl_CreateAccount.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_CreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CreateAccount.setText("click here to Create your account ...");
        lbl_CreateAccount.setNextFocusableComponent(txt_UserName);
        lbl_CreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CreateAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CreateAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CreateAccountMouseExited(evt);
            }
        });
        kGradientPanel_Bg.add(lbl_CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel_Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel_Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel_BgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel_BgMousePressed
        // TODO add your handling code here:
        new Drag(rootPane).onPress(evt);
    }//GEN-LAST:event_kGradientPanel_BgMousePressed

    private void kGradientPanel_BgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel_BgMouseDragged
        // TODO add your handling code here:
        new Drag(rootPane).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel_BgMouseDragged

    private void lbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseClicked
        // TODO add your handling code here:
        if (lbl_Close.isFocusable())
            if (JOptionPane.showConfirmDialog(null, "Do you want exit? (Yes/No)","Warning!", 0)==0)
                this.dispose();
        try {
            new Starting().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(UserLoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbl_CloseMouseClicked

    private void lbl_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseEntered
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.red);
    }//GEN-LAST:event_lbl_CloseMouseEntered

    private void lbl_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseExited
        // TODO add your handling code here:
        lbl_Close.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_CloseMouseExited

    private void lbl_CreateAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CreateAccountMouseEntered
        // TODO add your handling code here:
        lbl_CreateAccount.setFont(new Font("Tahoma",2,14));
        lbl_CreateAccount.setText("<html><u>"+lbl_CreateAccount.getText()+"</u></html>");
    }//GEN-LAST:event_lbl_CreateAccountMouseEntered

    private void lbl_CreateAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CreateAccountMouseExited
        // TODO add your handling code here:
        lbl_CreateAccount.setFont(new Font("Tahoma",2,14));
        lbl_CreateAccount.setText("click here to Create your account ...");
    }//GEN-LAST:event_lbl_CreateAccountMouseExited

    private void lbl_CreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CreateAccountMouseClicked
        // TODO add your handling code here:
        new RegistrationGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_CreateAccountMouseClicked

    private void txt_UserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_UserNameFocusGained
        // TODO add your handling code here:
        jLabel_UserName.setForeground(new Color(0, 204, 204));
        jLabel_Password.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_txt_UserNameFocusGained

    private void pas_UserPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pas_UserPasswordFocusGained
        // TODO add your handling code here:
        jLabel_UserName.setForeground(new Color(255, 255, 255));
        jLabel_Password.setForeground(new Color(0, 204, 204));
    }//GEN-LAST:event_pas_UserPasswordFocusGained

    private void btn_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogInActionPerformed
        // TODO add your handling code here:
        dao = new ServerDAO();
        String userName = txt_UserName.getText();
        String userPass = String.valueOf(pas_UserPassword.getPassword());
        
        if (txt_UserName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Username!");
        }
        else if (String.valueOf(pas_UserPassword.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null,"Enter Password!");
        }
        else if (dao.queryAccount(userName, userPass)){
//            UserAccount userLogIn = new UserAccount();
//            userLogIn.setUser_Username(userName);
//            userLogIn.setUser_Password(userPass);
            member = dao.getInfo(userName, userPass);
            
            //check-----------------------
//            JOptionPane.showMessageDialog(null, " "+userLogIn.getUser_MetBeforeQuestionID());
            
            new UserInfoGUI(member).setVisible(true); //Truyen tham so object member sau khi login thanh cong
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null,"Login Failed, try again!");
        }
        
    }//GEN-LAST:event_btn_LogInActionPerformed

    private void pas_UserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas_UserPasswordActionPerformed
        // TODO add your handling code here:
        btn_LogInActionPerformed(evt);
    }//GEN-LAST:event_pas_UserPasswordActionPerformed

    private void txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserNameActionPerformed
        // TODO add your handling code here:
        btn_LogInActionPerformed(evt);
    }//GEN-LAST:event_txt_UserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_LogIn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_UserName;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel_Bg;
    private javax.swing.JLabel lbl_Close;
    private javax.swing.JLabel lbl_CreateAccount;
    private javax.swing.JPasswordField pas_UserPassword;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
